version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
  aws-code-deploy: circleci/aws-code-deploy@1.0.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2-node
    steps:
      - checkout
      - ruby/install-deps
  test:
    # parallelism: 3
    docker:
      - image: cimg/ruby:3.1.2-node
      - image: cimg/postgres:15.0
        environment:
          POSTGRES_USER: postgres-circleci
          POSTGRES_DB: content_reels_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres-circleci
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mv config/database.yml.sample config/database.yml
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - aws-code-deploy/deploy:
          requires:
            - test