version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2

    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps
      # Run rspec
      - ruby/rspec-test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build